# automatically generated by the FlatBuffers compiler, do not modify

# namespace: guppy_ipc

class Content(object):
    NONE = 0
    SimpleRequestData = 1
    SimpleReplyData = 2
    ReadBlockData = 3
    ConfigData = 4
    ServerStats = 5

