# automatically generated by the FlatBuffers compiler, do not modify

# namespace: guppy_ipc

class ReadBlockType(object):
    PASS_FIRST_RAW_BLOCK = 0
    PASS_NEXT_RAW_BLOCK = 1
    RETURN_FIRST_CALLED_BLOCK = 2
    RETURN_NEXT_CALLED_BLOCK = 3

