# automatically generated by the FlatBuffers compiler, do not modify

# namespace: guppy_ipc

class SimpleReplyType(object):
    CONNECTED = 0
    DISCONNECTED = 1
    SHUTTING_DOWN = 2
    INVALID_CONFIG = 3
    INVALID_BARCODE_KIT = 4
    CLIENT_NOT_RECOGNISED = 5
    LOADING_CONFIG = 6
    RAW_BLOCK_ACCEPTED = 7
    NOT_READY = 8
    NONE_PENDING = 9
    BAD_REQUEST = 10
    BAD_REPLY = 11
    INVALID_INDEX = 12
    LOADING_INDEX = 13
    INVALID_BED = 14
    LOADING_BED = 15

